name: Validate the Packer Template
on:
  pull_request:
    branches: [main]
jobs:
  packer_init_validate:
    runs-on: ubuntu-latest
    name: Validate Packer
    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v2

      - name: Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: aws-ubuntu.pkr.hcl

      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: aws-ubuntu.pkr.hcl